### ISSUE TITLE
'document' type links 

### ISSUE THREAD

**Issue by whyte624** [helthe/Turbolinks#5]
When link returns response with attachment turbolinks.js doesn't remove loading indicator.

For example:
```
Response headers:
Content-Disposition:attachment; filename="report.pdf"
```

**Comment by carlalexander** [comment]
I think it's a bug that got fixed [here](https://github.com/rails/turbolinks/pull/441). Unfortunately, the rails Turbolinks library is in a phase of heavy development. They haven't made a release since December. 

You could try to compile their current `turbolinks.js.coffee` and see if it works. Otherwise, there isn't much I can do until they make a new release.
